version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/Chicago'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']
    commit-message:
      prefix: 'ci(deps)'
      prefix-development: 'ci(deps-dev)'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
